version: '3.4'

services:
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_api
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: bank_api_database
    ports:
      - "5432:5432"
    env_file:
      - .env

