"""teste

Revision ID: 12d52d37ed36
Revises: 40aa56ef5947
Create Date: 2022-06-10 11:24:13.419706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d52d37ed36'
down_revision = '40aa56ef5947'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
