"""create customer

Revision ID: 59218c393467
Revises: 
Create Date: 2022-06-08 12:15:04.458639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59218c393467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('udpated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_customer_uuid'), 'customer', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_uuid'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
