"""teste

Revision ID: ddf2756f0690
Revises: 12d52d37ed36
Create Date: 2022-06-10 11:25:46.048001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf2756f0690'
down_revision = '12d52d37ed36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_id', table_name='customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_id', 'customer', ['id'], unique=False)
    # ### end Alembic commands ###
